name = "case_study"
version = "0.1.0"
defaultTargets = ["CaseStudy"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "CaseStudy"

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "main" # Replace this with `rev = "v4.XX.X"` to add LeanHammer for an earlier supported Lean version.

[[require]]
name = "MyHammer"
git = "https://github.com/nartannt/LeanHammer"
rev = "main"
